import Scenes                                                                                                                                                                                                                                 
import Igis                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
class Background : RenderableEntity {                                                                                                                                                                                                         
                                                                                                                                                                                                                                              
    private var generationCount = 1                                                                                                                                                                                                           
    private var didRender = false                                                                                                                                                                                                             
                                                                                                                                                                                                        type annotation missing in pattern    
    init() {                                                                                                                                                                                                                                  
        super.init(name:"Background")                                                                                                                                                                                                         
    }                                                                                                                                                                                                                                         
    func clearCanvas(canvas:Canvas) {                                                                                                                                                                                                         
        if let canvasSize = canvas.canvasSize {                                                                                                                                                                                               
            let canvasRect = Rect(topLeft:Point(), size:canvasSize)                                                                                                                                                                           
            let canvasClearRectangle = Rectangle(rect:canvasRect, fillMode:.clear)                                                                                                                                                            
            canvas.render(canvasClearRectangle)                                                                                                                                                                                               
        }                                                                                                                                                                                                                                     
    }  
}
//test
